name: Flutter CI - Unit Tests
run-name: Deployed by @${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop" ]
    types: [labeled, opened, synchronize, reopened]

jobs:
  flutter_unit_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:  
      - name: Checkout the branch
        uses: actions/checkout@v3
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.7.0 
          cache: true
      
      - name: Get packages
        run: flutter pub get
      - name: Detect errors or inefficiencies
        run: flutter analyze --fatal-warnings
      - name: Run unit tests
        run: flutter test 
